/**
 * Shared types for the unit mock exam paper generated by Sayar Owl.
 * Used ONLY by the Syllabus Curriculum Explorer "AI grammar practice" flow.
 */

export type FillItem = { number: number; sentence: string; hint?: string; answer: string };
export type McqItem = {
  number: number;
  sentence: string;
  options: { label: string; text: string }[];
  answer: string;
};
export type TransformItem = {
  number: number;
  sentence: string;
  instruction: string;
  answer: string;
};
export type QaItem = { number: number; question: string; answer: string };
export type DefinitionItem = { number: number; definition: string; answer: string };
export type DialogueTurn = { number: number; speaker: string; text: string; answer?: string };

export type ExamSection =
  | { id: string; title: string; marks: number; instructions: string; type: "fill"; items: FillItem[] }
  | { id: string; title: string; marks: number; instructions: string; type: "mcq"; items: McqItem[] }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "transformation";
      items: TransformItem[];
    }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "poetry";
      poemTitle: string;
      partA: FillItem[];
      partB: QaItem[];
    }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "passage";
      passage: string;
      partA: FillItem[];
      partB: QaItem[];
    }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "passage_extended";
      passage: string;
      definitions: DefinitionItem[];
      distractorDefinition: string;
      partB: QaItem[];
    }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "functional";
      wordBank: string[];
      dialogue: DialogueTurn[];
      phraseBank: string[];
      matches: QaItem[];
    }
  | {
      id: string;
      title: string;
      marks: number;
      instructions: string;
      type: "writing";
      maxWords: number;
      prompts: string[];
      /** Optional sample answers aligned with each prompt (a, b, c…). */
      sampleAnswers?: string[];
    };

export type MockExamPaper = {
  title: string;
  unit: number;
  unitTopics: string;
  totalMarks: number;
  durationMinutes: number;
  sections: ExamSection[];
};
